CREATE TABLE "BOOKING" (
                           "ID" NUMBER(19,0),
                           "BOOKING_ID" VARCHAR2(255 CHAR) NOT NULL,
                           "FULL_NAME" VARCHAR2(255 CHAR) NOT NULL,
                           "EMAIL" VARCHAR2(255 CHAR) NOT NULL,
                           "CHECK_IN" DATE NOT NULL,
                           "CHECK_OUT" DATE NOT NULL,
                           "IS_CANCELLED" NUMBER(1,0) NOT NULL,
                           CONSTRAINT BOOKING PRIMARY KEY (ID)
);
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_ID_UNQ UNIQUE (BOOKING_ID);
CREATE SEQUENCE "BOOKING_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCYCLE;

CREATE TABLE "CAMP_BOOKING" (
                                "ID" NUMBER(19,0),
                                "BOOKING_ID" VARCHAR2(255 CHAR),
                                "DATE_" DATE NOT NULL,
                                "IS_AVAILABLE" NUMBER(1,0) DEFAULT 1 NOT NULL,
                                "VERSION"	NUMBER(24,0) DEFAULT 1 NOT NULL,
                                CONSTRAINT CAMP_BOOKING_PK PRIMARY KEY (ID)
);
ALTER TABLE CAMP_BOOKING ADD CONSTRAINT CAMP_BOOKING_DATE_UNQ UNIQUE (DATE_);
ALTER TABLE CAMP_BOOKING ADD CONSTRAINT CAMP_BOOKING_FK FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(BOOKING_ID);
CREATE SEQUENCE "CAMP_BOOKING_ID_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCYCLE;

DECLARE
    d_current_date DATE;
BEGIN
    d_current_date := trunc(SYSDATE);
    FOR i in 1 .. 365 LOOP
            insert into CAMP_BOOKING (ID,DATE_) values (CAMP_BOOKING_ID_SEQ.nextval,d_current_date+i);
    END LOOP;
    commit;
END;